services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - '.env'
    volumes:
      - database_pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure:3
  product-catalog:
    build:
      context: .
      dockerfile: apps/product-catalog/Dockerfile
    command:
      npm start product-catalog
      # container_name: medusa-server
    ports:
      - '4000:3000' # Expose the backend on port 4000
    depends_on:
      - postgres
volumes:
  database_pg:
